<?php
    //CREDENCIALES PARA HACER LA CONEXION A LA BASE DE DATOS
    $DATABASE_HOST='viaduct.proxy.rlwy.net';
    $DATABASE_USER='root';
    $DATABASE_PASS='CRmYPGUcWLZlFUTWwBNGNQwurtakBNdJ';
    $DATABASE_NAME='railway';
    $DATABASE_PORT='49922';

    //CONEXION A LA BASE DE DATOS...
    $conex = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME);

?>