<?php
    //CREDENCIALES PARA HACER LA CONEXION A LA BASE DE DATOS
    $DATABASE_HOST='';
    $DATABASE_USER='';
    $DATABASE_PASS='';
    $DATABASE_NAME='';

    //CONEXION A LA BASE DE DATOS...
    $conex = mysqli_connect($DATABASE_HOST, $DATABASE_USER, $DATABASE_PASS, $DATABASE_NAME);

?>
